# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j7 -l7"
EMERGE_DEFAULT_OPTS="--jobs=7 --load-average=7"

USE="dist-kernel wayland xwayland X gtk rust-src rust-analyzer persist bluetooth dvd 
pipewire pipewire-alsa screencast -systemd -gnome -qt -qt5 -qt6 -kde -plasma -aqua
-emacs -eds -telemetry -telepathy -gnome-online-accounts -extra -extras -cups"

ACCEPT_LICENSE="@FSF-APPROVED linux-fw-redistributable"
FEATURES="-getbinpkg -getbinpkgonly"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/ \
    https://br.mirrors.cicku.me/gentoo/ \
    https://umbriel.br.ext.planetunix.net/pub/gentoo/"
