[main]
font=monospace:size=11

[colors]
alpha=0.75
background = 000000
foreground = ffffff

# Branco (Cores primárias do texto)
regular0 = 2C363E
bright0 = deddda
regular1 = ffffff
bright1 = ffffff
regular2 = deddda
bright2 = deddda

regular7 = aaaaaa
bright7 = ffffff 

# Nord
#regular3 = AED5F5
#bright3  = AED5F5
#regular4 = 52A8F8
#bright4  = 52A8F8
#regular5 = 005197
#bright5  = 005197
#regular6 = 394988
#bright6  = 394988

# Rosé Ice
#regular3 = fdadc7
#bright3 = fdadc7
#regular4 = ea4c88
#bright4 =  ea4c88
#regular5 = abbcda
#bright5 =  abbcda
#regular6 = 82BCDA
#bright6 = 82BCDA

# Plains
#regular3 = D2C8BF
#bright3 = D2C8BF 
#regular4 = 6D8EB1
#bright4 =  6D8EB1
#regular5 = 8C873C
#bright5 =  8C873C
#regular6 = 777D51
#bright6 = 777D51

# Low Fire
#regular3 = ecc450
#bright3 = ecc450
#regular4 = eaa835
#bright4 = eaa835
#regular5 = EF670E
#bright5 = EF670E
#regular6 = DB5431
#bright6 = DB5431

# Vaporwave
#regular3 = 57A2DC
#bright3 = 57A2DC
#regular4 = 4A8BC9
#bright4 = 4A8BC9
#regular5 = BE64A5
#bright5 = BE64A5
#regular6 = A85B93
#bright6 = A85B93

# Synthwave
#regular3 = FF82CE
#bright3 =  FF82CE
#regular4 = FF5BC1
#bright4 = FF5BC1
#regular5 = 5549AB
#bright5 = 5549AB
#regular6 = 562BB8
#bright6 = 562BB8

# Salvation
regular3 = ECC450
bright3  = ECC450
regular4 = EAA835
bright4  = EAA835
regular5 = 00A4FF
bright5  = 00A4FF
regular6 = 014BAA
bright6  = 014BAA

# Red Bull
regular1 = 004adf
bright1 = 004adf
regular2 = 0439c5
bright2 = 0439c5
regular3 = ecc450
bright3 = ecc450
regular4 = eaa835
bright4 = eaa835
regular5 = fa0005
bright5 = fa0005
regular6 = d80401
bright6 = d80401
